export const pagesData = [
  {
    id: 0,
    name: 'Kitchen',
    slug: 'kitchen-designs',
    noItems: '2047',
    heading: 'Modular Kitchen Designs',
    desc: ' Get a Top Quality, functional, Affordable & Well Lit Modular Kitchen, using the Top Notch fittings. We Design from a basic simple modular kitchen to an exclusive luxury modular kitchen which perfects for convenience and aesthetics. All Our Modular Kitchens are budget friendly, and we assure you 100% guaranteed quotes across Delhi NCR, we have claimed for the past 9 years, that you bring us any Quote and we offer you Flat 7% off. We design your Modular Kitchen exactly as per bespoke requirements, in all shapes like L shape, G, U shape, Island kitchen, Open kitchen etc with distinctive types of finishes in acrylic, membrane, designer laminates, lacquer glass and veneer shutter. Check out some of the coolest kitchen designs we have with us.',
   
  },
  {
    id: 1,
    name: 'Vanities',
    slug: 'vanities',
    noItems: '2874',
    heading: 'Vanities',
    desc: 'We at Design Indian Homes design & manufacture beautiful affordable vanities which have dedicated functions like custom drawers, internal storages and with elegant handles. All Our Bathroom Vanities are economical and delivered on a very timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off.',
    items: [],
  },
  {
    id: 2,
    name: 'Crockery Units',
    slug: 'crockery-units',
    noItems: '1816',
    heading: 'Crockery Units',
    desc: 'Now get a Bespoke Crockery Unit with our team, we have a myriad range of Crockery Unit designs with glass, acrylics and premium Fenix materials. All Our Crockery Units are very pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we have claimed since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, Stone Veneers, Glass Acrylics and lacquer glass. Check out our designs for some of the top ideas for your Crockery Units.',
    items: [],
  },
  {
    id: 3,
    name: 'Glass Partiton',
    slug: 'glass-partiton',
    noItems: '162',
    heading: 'Glass Partition',
    desc: 'When you really deserve a perfect partition, you must get one. Now get Beautiful Glass Partitions for your interiors to deck up your spaces. Delight yourself in our products, All Our Glass Partitions are very pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like slim profiled, zed profiled, cube profile and lacquered. Check out our designs for some of the top ideas for your Glass Partitions.',
    items: [],
  },
  {
    id: 4,
    name: 'Dressers',
    slug: 'dressers',
    noItems: '809',
    heading: 'Dressers',
    desc: 'We make you look good, by having good looking Dressers… ! Now get a bespoke dresser, made specifically as per your requirements at the most affordable quotes. All Our Dressers are very economical and delivered on a very timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we have claimed since past 9 years, that you bring us any Quote and we offer you Flat 7% off.We provide different finishes of the shutter, stone veneers, glass acrylics and lacquer glass. Check out our designs for some of the top ideas for your dressers.',
    items: [],
  },
  {
    id: 5,
    name: 'Wardrobe',
    slug: 'wardrobe',
    noItems: '1165',
    heading: 'Wardrobe Interior Designs',
    desc: 'We make your wardrobes look good, just as you dress up to look up, we are your Wardrobe’s Makeover Specialist. All Our Wardrobes are very affordable and we have more than 1000+ wardrobe designs to showcase, book a site visit with us and see the design magic, and we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off. Check out our designs for best Wardrobe Ideas and Inspirations.',
    items: [],
  },
  {
    id: 6,
    name: 'Tv unit designs',
    slug: 'tv-unit-designs',
    noItems: '1012',
    heading: 'Modular TV Unit Design Ideas',
    desc: 'Hey ! I feel like I can look at it for ages, that’s how your friends and family will exclaim after you have a TV unit from our Brand Design Indian Homes. All Our TV Units are very pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we have claimed since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, Stone Veneers, Glass Acrylics and Tinted mirrors. Check out our designs for some of the top ideas for your TV Units.',
    items: [],
  },

]
