export const pagesData = [
  {
    id: 0,
    name: ' Mandir',
    slug: 'mandir',
    noItems: '2047',
    heading: 'Mandir',
    desc: 'We take keen interest in delivering graceful Mandirs. We have a huge range of mandir designs for your interiors. Check out our Mandir section for a huge range of Temple designs & get a Temple today at an affordable price which can be customized as per your design. Delight yourself in our products, All Our Mandir Units are very pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off.',
    items: [],
  },
  {
    id: 1,
    name: 'Chest of Drawers',
    slug: 'chest-of-drawers',
    noItems: '2874',
    heading: 'Chest of Drawers',
    desc: ' Get Beautiful designed Chest of Drawers by our design team to spice up your living areas or Bedrooms. Some of the classic chest of drawers are manufactured by our Brand, book a visit by our Team Today. Take Delight in our products, All Our Chest of Drawers are pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, Stone Veneers, Glass Acrylics and lacquer glass. Check out our designs for some of the top ideas for your Chest of Drawers.',
    items: [],
  },
  {
    id: 2,
    name: 'Bar Units',
    slug: 'bar-units',
    noItems: '1816',
    heading: 'Bar Units',
    desc: ' We have some exquisite designs for Bar Units, we can provide you some of the most creative bar designs to liven up your parties. We design bespoke bar units with different types of storage making it aesthetic for wine bottles, glass cups and for built-in chillers if required. Take Delight in our products, All Our Bar Units are pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since the past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, teak, Stone Veneers, Glass Acrylics and lacquer glass. Check out our designs for some of the top ideas for your Bar Units.',
    items: [],
  },
  {
    id: 3,
    name: 'Side Tables',
    slug: 'side-tables',
    noItems: '162',
    heading: 'Side Tables',
    desc: 'An Amazing Makeover for Your Bed Side Tables, Now get a customized designed side table by design Indian homes at most affordable prices. We have a huge range of drawers fitting and designers shutter options for your side tables. Check out our latest design today. Take Delight in our products, All Our Side Tables are pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, teak, Stone Veneers, Glass Acrylics and lacquer glass. Check out our designs for some of the top ideas for your Side Tables.',
    items: [],
  },
  {
    id: 4,
    name: 'Foldable Beds',
    slug: 'foldable-beds',
    noItems: '809',
    heading: 'Foldable Beds',
    desc: 'Now that is a Masterpiece and a Space Saver, Get a design by our team for your customized foldable bed with storage for space saving in your bedroom with different finishes. Check out our topmost foldable beds design. Take Delight in our products, All Our Foldable Bed Designs are pocket friendly and delivered on timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, teak, Stone Veneers, Glass Acrylics and lacquer glass. Check out our designs for some of the top ideas for your Foldable Beds.',
    items: [],
  },
  {
    id: 5,
    name: 'Foyer Cabinets',
    slug: 'foyer-cabinets',
    noItems: '1165',
    heading: 'Foyer Cabinets',
    desc: 'A Grand Entry for your Entrances, Now Get a designer foyer area with a beautiful chest of drawers and assorted wall panelling and lightning solutions as per custom design. Check out our beautiful foyer area designs for your interiors. Take Delight in our products, All Our Foyer Area Designs are pocket friendly and delivered on timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, teak, Stone Veneers, Glass Acrylics and lacquer glass. Check out our designs for some of the top ideas for your Foyer Area.',
    items: [],
  },
  {
    id: 6,
    name: 'Bathroom Vanities',
    slug: 'bathroom-vanities',
    noItems: '1012',
    heading: 'Bathroom Vanities',
    desc: 'Trending TV unit designs from Design Indian Homes that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Design Indian Homes helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  // {
  //   id: 7,
  //   name: 'studio apartment interior designs',
  //   slug: 'studio-apartment-interior-designs',
  //   noItems: '1012',
  //   heading: 'studio apartment interior designs',
  //   desc: 'Trending TV unit designs from Design Indian Homes that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Design Indian Homes helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
  //   items: [],
  // },
  // {
  //   id: 8,
  //   name: 'Bunglow interior designs',
  //   slug: 'bunglow-interior-designs',
  //   noItems: '1012',
  //   heading: 'Bunglow interior designs',
  //   desc: 'Trending TV unit designs from Design Indian Homes that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Design Indian Homes helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
  //   items: [],
  // },
  // {
  //   id: 9,
  //   name: 'Duplex Residence interior designs',
  //   slug: 'duplex-residence-interior-designs',
  //   noItems: '1012',
  //   heading: 'Duplex Residence interior designs',
  //   desc: 'Trending TV unit designs from Design Indian Homes that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Design Indian Homes helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
  //   items: [],
  // },
  // {
  //   id: 10,
  //   name: 'Cottage interior designs',
  //   slug: 'cottage-interior-designs',
  //   noItems: '1012',
  //   heading: 'Cottage interior designs',
  //   desc: 'Trending TV unit designs from Design Indian Homes that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Design Indian Homes helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
  //   items: [],
  // },


]
